spring.application.name=usuarios-service-pedidos360
server.port=8081

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/3441157d-ea5c-483f-a66d-e45c3ed7f9da/v2.0
pedidos360.security.jwt.audience=5582b6c4-7ecd-4bed-9337-ba3f1f8e58e5

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
